
let colors = [
    "#FF0000",
    "#0033FF",
    "#009900",
    "#00FF00",
    "#6633FF",
    "#990000",
    "#000000",
    "#66FFFF",
    "#999933",
    "#FFFF00",
    "#996699",
    "#FF9900",
    "#84C1FF",
    "#C0C0C0",
    "#FF00FF",
    "#FF6666",
    "#00CC99",
    "#CC6600",
    "#CCFF99",
    "#CCCCFF",
    "#FF0080",
    "#32A9D6",
    "#6E6E6E",
    "#339933",
    "#339933",
    "#339933",
    "#339933",
    "#339933",
    "#339933",
];



export const dataConfig = [


    /*
        //{key:'sumDate',name:"sumDate",color:colors[0]},
        //{key:'graphDate',name:"graphDate",color:colors[1]},
        //{key:'logDate',name:"logDate",color:colors[2]},
        //{key:'pid',name:"pid",color:colors[3]},
        //{key:'newUserCount',name:"新增用户数量",color:colors[4]},
        //{key:'androidNewUserCount',name:"安卓新增用户数量",color:colors[5]},
        //{key:'iosNewUserCount',name:"ios新增用户数量",color:colors[6]},
        ////{key:'WebNewUserCount',name:"WebNewUserCount",color:colors[7]},
        //{key:'loginUserCount',name:"登录人数",color:colors[8]},
        //{key:'androidLoginUserCount',name:"安卓登录人数",color:colors[9]},
        //{key:'iosLoginUserCount',name:"ios登录人数",color:colors[10]},
        ////{key:'WebLoginUserCount',name:"WebLoginUserCount",color:colors[11]},
        //{key:'watchUserCount',name:"观影人数",color:colors[12]},
        //{key:'androidWatchUserCount',name:"安卓观影人数",color:colors[13]},
        //{key:'iosWatchUserCount',name:"ios观影人数",color:colors[14]},
        ////{key:'WebWatchUserCount',name:"WebWatchUserCount",color:colors[15]},
        //{key:'totalChargeAmt',name:"总充值",color:colors[16]},
        //{key:'totalChargeCount',name:"总充值订单数",color:colors[17]},
        ////{key:'totalChargeUserCount',name:"totalChargeUserCount",color:colors[18]},
        //{key:'diamondChargeAmt',name:"钻石充值",color:colors[19]},
        //{key:'diamondChargeCount',name:"钻石充值单数",color:colors[20]},
        ////{key:'diamondChargeUserCount',name:"diamondChargeUserCount",color:colors[21]},
        //{key:'vipChargeAmt',name:"vip充值",color:colors[0]},
        //{key:'vipChargeCount',name:"vip充值单数",color:colors[0]},
        ////{key:'vipChargeUserCount',name:"vipChargeUserCount",color:colors[0]},
        //{key:'androidTotalChargeAmt',name:"安卓总充值数",color:colors[0]},
        //{key:'androidTotalChargeCount',name:"",color:colors[0]},
        ////{key:'androidTotalChargeUserCount',name:"androidTotalChargeUserCount",color:colors[0]},
        //{key:'androidDiamondChargeAmt',name:"安卓钻石充值",color:colors[0]},
        //{key:'androidDiamondChargeCount',name:"安卓钻石订单数",color:colors[0]},
        ////{key:'androidDiamondChargeUserCount',name:"androidDiamondChargeUserCount",color:colors[0]},
        //{key:'androidVipChargeAmt',name:"安卓vip充值",color:colors[0]},
        //{key:'androidVipChargeCount',name:"安卓vip订单数",color:colors[0]},
        ////{key:'androidVipChargeUserCount',name:"androidVipChargeUserCount",color:colors[0]},
        //{key:'iosTotalChargeAmt',name:"ios充值",color:colors[0]},
        //{key:'iosTotalChargeCount',name:"ios订单数",color:colors[0]},
        ////{key:'iosTotalChargeUserCount',name:"iosTotalChargeUserCount",color:colors[0]},
        //{key:'iosDiamondChargeAmt',name:"ios钻石充值",color:colors[0]},
        //{key:'iosDiamondChargeCount',name:"ios钻石订单数",color:colors[0]},
        ////{key:'iosDiamondChargeUserCount',name:"iosDiamondChargeUserCount",color:colors[0]},
        //{key:'iosVipChargeAmt',name:"iosVip充值",color:colors[0]},
        //{key:'iosVipChargeCount',name:"iosVip订单数",color:colors[0]},
        ////{key:'iosVipChargeUserCount',name:"iosVipChargeUserCount",color:colors[0]},
    */


    { key: 'newUserCount', name: "总新增用户数量", color: colors[4] },
    { key: 'loginUserCount', name: "总登录人数", color: colors[8] },
    { key: 'watchUserCount', name: "总观影人数", color: colors[12] },
    // { key: 'totalChargeAmt', name: "总充值", color: colors[16] },
    // { key: 'totalChargeCount', name: "总充值订单数", color: colors[17] },
    // { key: 'diamondChargeAmt', name: "总钻石充值", color: colors[19] },
    // { key: 'diamondChargeCount', name: "总钻石充值单数", color: colors[20] },
    // { key: 'vipChargeAmt', name: "总vip充值", color: colors[0] },
    // { key: 'vipChargeCount', name: "总vip充值单数", color: colors[0] },
    { key: 'androidNewUserCount', name: "安卓新增用户数", color: colors[5] },
    { key: 'androidLoginUserCount', name: "安卓登录人数", color: colors[9] },
    { key: 'androidWatchUserCount', name: "安卓观影人数", color: colors[13] },
    // { key: 'androidTotalChargeAmt', name: "安卓总充值", color: colors[0] },
    // { key: 'androidTotalChargeCount', name: "安卓总订单", color: colors[0] },
    // { key: 'androidDiamondChargeAmt', name: "安卓钻石充值", color: colors[0] },
    // { key: 'androidDiamondChargeCount', name: "安卓钻石订单数", color: colors[0] },
    // { key: 'androidVipChargeAmt', name: "安卓vip充值", color: colors[0] },
    // { key: 'androidVipChargeCount', name: "安卓vip订单数", color: colors[0] },
    { key: 'iosNewUserCount', name: "ios新增用户数量", color: colors[6] },
    { key: 'iosLoginUserCount', name: "ios登录人数", color: colors[10] },
    { key: 'iosWatchUserCount', name: "ios观影人数", color: colors[14] },
    // { key: 'iosTotalChargeAmt', name: "ios充值", color: colors[0] },
    // { key: 'iosTotalChargeCount', name: "ios订单数", color: colors[0] },
    // { key: 'iosDiamondChargeAmt', name: "ios钻石充值", color: colors[0] },
    // { key: 'iosDiamondChargeCount', name: "ios钻石订单数", color: colors[0] },
    // { key: 'iosVipChargeAmt', name: "iosVip充值", color: colors[0] },
    // { key: 'iosVipChargeCount', name: "iosVip订单数", color: colors[0] },



];

export const dataConfig_recharge = [
    { key: 'totalChargeAmt', name: "总充值", color: colors[16], type: 'bar' },
    { key: 'vipChargeAmt', name: "总vip充值", color: colors[0], type: 'bar' },
    { key: 'androidTotalChargeAmt', name: "安卓总充值", color: colors[0], type: 'bar' },
    { key: 'androidDiamondChargeAmt', name: "安卓钻石充值", color: colors[0], type: 'bar' },
    { key: 'androidVipChargeAmt', name: "安卓vip充值", color: colors[0], type: 'bar' },
    { key: 'iosTotalChargeAmt', name: "ios充值", color: colors[0], type: 'bar' },
    { key: 'iosDiamondChargeAmt', name: "ios钻石充值", color: colors[0], type: 'bar' },
    { key: 'iosVipChargeAmt', name: "iosVip充值", color: colors[0], type: 'bar' },
    { key: 'diamondChargeAmt', name: "总钻石充值", color: colors[19], type: 'bar' },
    { key: 'diamondChargeCount', name: "总钻石充值单数", color: colors[20], type: 'line' },
    { key: 'totalChargeCount', name: "总充值订单数", color: colors[17], type: 'line' },
    { key: 'vipChargeCount', name: "总vip充值单数", color: colors[0], type: 'line' },
    { key: 'androidTotalChargeCount', name: "安卓总订单", color: colors[0], type: 'line' },
    { key: 'androidDiamondChargeCount', name: "安卓钻石订单数", color: colors[0], type: 'line' },
    { key: 'androidVipChargeCount', name: "安卓vip订单数", color: colors[0], type: 'line' },
    { key: 'iosTotalChargeCount', name: "ios订单数", color: colors[0], type: 'line' },
    { key: 'iosDiamondChargeCount', name: "ios钻石订单数", color: colors[0], type: 'line' },
    { key: 'iosVipChargeCount', name: "iosVip订单数", color: colors[0], type: 'line' },

];

export const configNames = dataConfig.map(item => {
    return item.name;
});